### ISSUE TITLE
Server Data/Architecture

### ISSUE THREAD

**Issue by AlbertStoykov** [Prishal-git/Lap1Project#17]
THIS IS ALL DONE THROUGH LOCAL STORAGE - SHOULD FOCUS ON THIS NEAR END

We will need to create a base class object that has the following keys:

- postID - Integer
- postTitle - String
- postBody - ?
- timeStamp - ?
- emojiOne - Integer
- emojiTwo - Integer
- emojiThree - Integer
- comments - Object with three keys (commentID- integer, commentBody - String, commentTimeStamp - ?)

Each post will be an object derived from the base class.

**Comment by Prishal-git** [comment]
If we store the data locally then it will not be available for other users. Can we not store the data on the server and use the API fetch POST to send and store that data into the Json file? (I haven't looked into this if it is possible)
